#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

// LAYERS GO HERE 

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x5_2(KC_Q, KC_C, KC_H, KC_P, KC_V, KC_K, KC_Y, KC_O, KC_J, KC_BSPC, KC_R, KC_S, KC_N, KC_T, KC_G, KC_W, KC_U, KC_E, KC_A, KC_I, LALT_T(KC_X), KC_M, KC_L, KC_D, KC_B, KC_Z, KC_F, KC_COMM, KC_DOT, LGUI_T(KC_SLSH), MEH_T(KC_SPC), KC_LSFT, KC_LCTL, TO(1)),
	[1] = LAYOUT_split_3x5_2(KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_BSPC, KC_0, KC_LBRC, KC_LCBR, KC_LPRN, KC_DEL, KC_SCLN, KC_EQL, KC_MINS, KC_QUOT, KC_ENT, LALT_T(TO(2)), KC_RBRC, KC_RCBR, KC_RPRN, KC_NUBS, KC_BSLS, KC_RCBR, KC_RPRN, KC_GRV, LGUI_T(TO(3)), TO(0), KC_LSFT, KC_LCTL, TO(1)),
	[2] = LAYOUT_split_3x5_2(KC_ESC, KC_NO, KC_MS_U, KC_WH_U, KC_MS_L, KC_PGUP, KC_NO, KC_UP, KC_NO, KC_BSPC, KC_TAB, KC_MS_L, KC_MS_D, KC_MS_R, KC_DEL, KC_PGDN, KC_LEFT, KC_DOWN, KC_RGHT, KC_ENT, LALT_T(TO(2)), KC_WH_L, KC_WH_R, KC_WH_D, KC_MS_R, KC_NO, KC_ACL0, KC_ACL1, KC_ACL2, LGUI_T(TO(3)), TO(0), KC_LSFT, KC_LCTL, TO(1)),
	[3] = LAYOUT_split_3x5_2(KC_ESC, KC_BRIU, KC_VOLU, KC_MNXT, KC_NO, KC_F12, KC_F7, KC_F8, KC_F9, KC_BSPC, KC_TAB, KC_BRID, KC_VOLD, KC_MPRV, KC_NO, KC_F11, KC_F4, KC_F5, KC_F6, KC_ENT, LALT_T(TO(2)), KC_NO, KC_MUTE, KC_MSTP, KC_MPLY, KC_F10, KC_F1, KC_F2, KC_F3, LGUI_T(TO(3)), TO(0), KC_LSFT, KC_LCTL, TO(1))
};

// CUSTOM KEYCODES GO HERE



// tapdance keycodes
enum td_keycodes {
  ALT_LP // Our example key: `LALT` when held, `(` when tapped. Add additional keycodes for each tapdance.
};

// define a type containing as many tapdance states as you need
typedef enum {
  SINGLE_TAP,
  SINGLE_HOLD,
  DOUBLE_SINGLE_TAP
} td_state_t;

// create a global instance of the tapdance state type
static td_state_t td_state;

// declare your tapdance functions:

// function to determine the current tapdance state
int cur_dance (qk_tap_dance_state_t *state);

// `finished` and `reset` functions for each tapdance keycode
void altlp_finished (qk_tap_dance_state_t *state, void *user_data);
void altlp_reset (qk_tap_dance_state_t *state, void *user_data);
